### ISSUE TITLE
Speed sensors instead of wheel encoders (Gear-motor-encoder from Neato XV-11)

### ISSUE THREAD

**Issue by SystemDiagnosticss** [mikeferguson/neato_robot#9]
Hello. I have two gear-motor-encoder from Neato XV-11. But this motors actually not has encoders. He has speed sensors on Hall effect. 
He has only 5 wires from every motor (not 6 like in real motor-encoder). That's mean I can measure only speed and can't measure direction rotation.

Questions: What I must change in navigation stack for use this motors?? How are you doing this??  Thank's.
PS: Sorry for my English:)

**Comment by mikeferguson** [comment]
I have no idea -- this package is intended to control a complete Neato XV-11, not a disassembled portion.

**Comment by stephen-derosa** [comment]
@SystemDiagnosticss I am trying to hack this thing apart to and have found the same thing...I am going to attempt to power the motor and read both `A` and `B` terminals with a spectrometer but I am not sure how this will turn out.

Have you had any luck with this somewhere else on the web?
